// Gesture-gated synthesized audio. No downloads or copyrighted recordings.
export class GameAudio {
  constructor(){this.ctx=null;this.volume=.55;this.enabled=true;this.music=false;this.nextBeat=0;}
  async unlock(){try{if(!this.ctx){this.ctx=new(window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.master.connect(this.ctx.destination);this.master.gain.value=this.enabled?this.volume:0;const n=this.ctx.sampleRate*.35;this.noise=this.ctx.createBuffer(1,n,this.ctx.sampleRate);const b=this.noise.getChannelData(0);for(let i=0;i<n;i++)b[i]=Math.random()*2-1;}if(this.ctx.state==='suspended')await this.ctx.resume();}catch{}}
  set(v,on){this.volume=v;this.enabled=on;if(this.master)this.master.gain.setTargetAtTime(on?v:0,this.ctx.currentTime,.04);}
  tone(freq,duration=.15,volume=.15,type='sine',end=null){if(!this.ctx||this.ctx.state!=='running')return;const t=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(end)o.frequency.exponentialRampToValueAtTime(end,t+duration);g.gain.setValueAtTime(volume,t);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(this.master);o.start(t);o.stop(t+duration);o.onended=()=>{o.disconnect();g.disconnect();};}
  burst(duration,volume,cutoff=2000){if(!this.ctx||!this.noise)return;const t=this.ctx.currentTime,s=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();s.buffer=this.noise;f.type='lowpass';f.frequency.value=cutoff;g.gain.setValueAtTime(volume,t);g.gain.exponentialRampToValueAtTime(.001,t+duration);s.connect(f);f.connect(g);g.connect(this.master);s.start(t);s.stop(t+duration);s.onended=()=>{s.disconnect();f.disconnect();g.disconnect();};}
  play(e){if(!this.ctx)return;switch(e.type){case'shot':if(e.weapon===0){this.burst(.12,.12,1700);}else{this.burst(e.weapon===3?.16:.12,.38,2100);this.tone(130,.12,.3,'triangle',35);}break;case'enemyShot':this.burst(.08,.1/(1+e.distance*.16),1400);break;case'pickup':this.tone(660,.17,.12,'sine',1100);break;case'secret':this.tone(400,.8,.18,'triangle',900);break;case'door':this.burst(.3,.12,400);this.tone(90,.35,.06,'sawtooth',50);break;case'locked':case'empty':this.tone(120,.1,.1,'square');break;case'damage':this.burst(.11,.15,350);break;case'kill':this.tone(140,.2,.09,'triangle',70);break;case'complete':this.tone(400,.9,.15,'triangle',1300);break;case'dead':this.tone(160,1.1,.15,'sawtooth',35);break;}}
  step(){this.burst(.06,.035,550);}
  ambience(time){if(!this.music||time<this.nextBeat)return;this.nextBeat=time+1.6;const notes=[55,55,65.4,49,55,73.4,65.4,49];this.tone(notes[Math.floor(time/1.6)%notes.length],1.5,.035,'triangle');}
  dispose(){this.ctx?.close().catch(()=>{});}
}
